### ISSUE TITLE
Render file error: No such file or directory

### ISSUE THREAD

**Issue by mhf-ir** [phug-php/phug#9]
```
<?php
       // require auto load

        $data = \Phug\Phug::renderFile('/app/templates/index.pug');

        echo ($data);
```

```
Message: fopen(/app/vendor/phug/renderer/src/Phug/Renderer/Adapter/EvalAdapter.php(12) : eval()'d code): failed to open stream: No such file or directory
File: /app/vendor/phug/formatter/src/Phug/Formatter.php:158
Trace: #0 [internal function]: AasaamApp\Container\Error500->AasaamApp\Container\{closure}(2, 'fopen(/app/...', '/app/vendor...', 158, Array)
#1 /app/vendor/phug/formatter/src/Phug/Formatter.php(158): fopen('/app/vendor...', 'r')
#2 /app/vendor/phug/formatter/src/Phug/Formatter.php(210): Phug\Formatter->fileContains('/app/vendor...', 'PUG_DEBUG:')
#3 /app/vendor/phug/formatter/src/Phug/Formatter.php(252): Phug\Formatter->getSourceLine(Object(ErrorException))
#4 /app/vendor/phug/renderer/src/Phug/Renderer/Partial/Debug/DebuggerTrait.php(203): Phug\Formatter->getDebugError(Object(ErrorException), '<?php \n\\Phug\\Re...', '/app/etc/ph...')
#5 /app/vendor/phug/renderer/src/Phug/Renderer/Partial/Debug/DebuggerTrait.php(317): Phug\Renderer->getDebuggedException(Object(ErrorException), 1, '<?php \n\\Phug\\Re...', '/app/etc/ph...', Array, Array)
#6 /app/vendor/phug/renderer/src/Phug/Renderer.php(311): Phug\Renderer->handleError(Object(ErrorException), 1, '/app/etc/ph...', '<?php \n\\Phug\\Re...', Array, Array)
#7 /app/vendor/phug/renderer/src/Phug/Renderer.php(397): Phug\Renderer->callAdapter('render', '/app/etc/ph...', NULL, Object(Closure), Array)
#8 /app/vendor/phug/phug/src/Phug/Phug.php(248): Phug\Renderer->renderFile('/app/etc/ph...', Array)
```

**Comment by kylekatarnls** [comment]
This error message means `/app/templates/index.pug` does not exist or is not the valid path to the file you're looking for. Are you sure your would'nt get a relative path?

```$data = \Phug\Phug::renderFile('app/templates/index.pug');```

**Comment by mhf-ir** [comment]
`index.pug`:

```
p #{name}'s Pug source code!
```

`app.php`:

```
        $file = '/absolute/path/index.pug';
        var_dump(file_exists($file)); // true
        var_dump(is_readable($file)); // true
        $data = \Phug\Phug::renderFile($file);
```
Same error.

It's inside docker container i use absolute path and file exist and readable.
PHP 7.1
ubuntu 16.04

**Comment by mhf-ir** [comment]
With this pug template problem solved.
```
body
  h1 Phug
```

**Comment by mhf-ir** [comment]
Seems be different syntax between `pug` and `phug`. right?

**Comment by kylekatarnls** [comment]
The class `Pug\Pug` extends the `Phug\Renderer` and only provides some backward compatibilities from the pug-php version 2. So it should be pretty close.

Moreover, the template content should have no impact. Can you show me the difference between the working PHP code and the one that failed?

**Comment by mhf-ir** [comment]
Error
```
        echo Phug::display('p #{name}s Pug source code! $message', [
          'message' => 'Hello',
        ]);
```

Work well
```
        echo Phug::display('p Pug source code! $message', [
          'message' => 'Hello',
        ]);
```

**Comment by kylekatarnls** [comment]
It seems not related to the first error message. I presume, it's about missing variables or expression syntax style. Could you report this in another issue with the new error message and so I'll close this issue?
